### ISSUE TITLE
Is it possible to configure toolbar to be shown before text area?

### ISSUE THREAD

**Issue by leandrochristen** [iget-master/iget-editor#10]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [X] Feature request
- [ ] Documentation issue or request

Is it possible to configure toolbar to be shown before text area?

**Comment by iget-esoares** [comment]
Currently it's not possible, but it's a nice and easy feature. I'll work on it soon.

Also, Feel free to contribute with a pull request if you want.

**Comment by iget-master** [comment]
@leandrochristen This feature was released in v13.2.0.
